import { Skills } from "./Types";

export const skills: Skills = {
  Frontend: [
    { name: "HTML5", icon: "/html5.svg" },
    { name: "CSS3", icon: "/css3.svg" },
    { name: "Bootstrap", icon: "/bootstrap.svg" },
    { name: "Tailwind CSS", icon: "/tailwind.svg" },
    { name: "JavaScript (ES6+)", icon: "/javascript.svg" },
    { name: "TypeScript", icon: "/typescript.svg" },
    { name: "React.js", icon: "/react.svg" },
    { name: "Next.js", icon: "/icons/nextjs.svg" },
    { name: "MUI", icon: "/icons/mui.svg" },
    { name: "Redux Toolkit", icon: "/icons/redux.svg" },
    { name: "Framer Motion", icon: "/icons/framer-motion.svg" },
  ],
  Backend: [
    { name: "Node.js", icon: "/icons/nodejs.svg" },
    { name: "Express.js", icon: "/icons/express.svg" },
    { name: "Firebase", icon: "/icons/firebase.svg" },
    { name: "PostgreSQL", icon: "/icons/postgresql.svg" },
    { name: "MongoDB", icon: "/icons/mongodb.svg" },
    { name: "Sequelize ORM", icon: "/icons/sequelize.svg" },
    { name: "Prisma ORM", icon: "/icons/prisma.svg" },
    { name: "RESTful APIs", icon: "/icons/api.svg" },
    { name: "WebSockets", icon: "/icons/websocket.svg" },
    { name: "WebRTC", icon: "/icons/webrtc.svg" },
  ],
  DevOps: [
    { name: "Docker", icon: "/icons/docker.svg" },
    { name: "Kubernetes", icon: "/icons/kubernetes.svg" },
    { name: "AWS (S3, EKS)", icon: "/icons/aws.svg" },
    { name: "GCP", icon: "/icons/gcp.svg" },
    { name: "Git & GitHub", icon: "/icons/github.svg" },
    { name: "GitHub Actions", icon: "/icons/github-actions.svg" },
    { name: "Cloudflare", icon: "/icons/cloudflare.svg" },
    { name: "CI/CD", icon: "/icons/cicd.svg" },
    { name: "Webpack", icon: "/icons/webpack.svg" },
    { name: "Babel", icon: "/icons/babel.svg" },
    { name: "NPM", icon: "/icons/npm.svg" },
  ],
  Systems: [
    { name: "C Programming", icon: "/icons/c.svg" },
    { name: "C++", icon: "/icons/cpp.svg" },
    { name: "Java", icon: "/icons/java.svg" },
    { name: "Operating Systems", icon: "/icons/os.svg" },
    { name: "Data Structures & Algorithms", icon: "/icons/algorithms.svg" },
    { name: "System Design", icon: "/icons/design.svg" },
    { name: "In‑memory Caching", icon: "/icons/cache.svg" },
    { name: "Networking Concepts", icon: "/icons/network.svg" },
  ],
};
